# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 934c5591716901d7332ecd8c9564706a8c99a6b473effbc619571bb72240f967eca97280adc3c16a08e79dd70eb69cfa89b858a82132a1cba184cda9df5671d3

test:
  secret_key_base: 186de4dc2ef65ab6aeefc0d765888ad03dcfff1c5f42b715b17a4cd621d1b46280834cfbb364eb88b79ede34346bc520e7b1444484e1ed9b72cb5725518f1adc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
